#! /bin/bash
rm *.t
times=10
for i in {1..$times..1}
do
	./test-con-q-2 --Nprods 1 --Nconsm 1 --Nops 500000 >> hTest2_nn.t
	./test-con-q-4 --Nprods 2 --Nconsm 2 --Nops 500000 >> hTest4_nn.t
	./test-con-q-8 --Nprods 4 --Nconsm 4 --Nops 500000 >> hTest8_nn.t
done

for i in {1..$times..1}
do
	./test-con-q-4 --Nprods 1 --Nconsm 3 --Nops 500000 >> hTest4_1n.t
	./test-con-q-8 --Nprods 1 --Nconsm 7 --Nops 500000 >> hTest8_1n.t
done

for i in {1..$times..1}
do
	./test-con-q-4 --Nprods 3 --Nconsm 1 --Nops 500000 >> hTest4_n1.t
	./test-con-q-8 --Nprods 7 --Nconsm 1 --Nops 500000 >> hTest8_n1t
done


for i in {1..$times..1}
do
	start=$(date +%s.%N); \
	java SynchronousQueueTest 1 1 500000 500000
	dur=$(echo "$(date +%s.%N) - $start" | bc); \
	echo $dur >> jOut2_nn.t

	start=$(date +%s.%N); \
	java SynchronousQueueTest 2 2 500000 500000
	dur=$(echo "$(date +%s.%N) - $start" | bc); \
	echo $dur >> jOut4_nn.t

	start=$(date +%s.%N); \
	java SynchronousQueueTest 4 4 500000 500000
	dur=$(echo "$(date +%s.%N) - $start" | bc); \
	echo $dur >> jOut8_nn.t

	start=$(date +%s.%N); \
	java SynchronousQueueTest 8 8 500000 500000
	dur=$(echo "$(date +%s.%N) - $start" | bc); \
	echo $dur >> jOut16_nn.t

	start=$(date +%s.%N); \
	java SynchronousQueueTest 1 3 1500000 500000
	dur=$(echo "$(date +%s.%N) - $start" | bc); \
	echo $dur>> jOut4_1n.t

	start=$(date +%s.%N); \
	java SynchronousQueueTest 1 7 3500000 500000
	dur=$(echo "$(date +%s.%N) - $start" | bc); \
	echo $dur >> jOut8_1n.t

	start=$(date +%s.%N); \
	java SynchronousQueueTest 1 15 7500000 500000
	dur=$(echo "$(date +%s.%N) - $start" | bc); \
	echo $dur >> jOut16_1n.t

	start=$(date +%s.%N); \
	java SynchronousQueueTest 3 1 500000 1500000
	dur=$(echo "$(date +%s.%N) - $start" | bc); \
	echo $dur >> jOut4_n1.t

	start=$(date +%s.%N); \
	java SynchronousQueueTest 7 1 500000 3500000
	dur=$(echo "$(date +%s.%N) - $start" | bc); \
	echo $dur >> jOut8_n1.t

	start=$(date +%s.%N); \
	java SynchronousQueueTest 7 1 500000 7500000
	dur=$(echo "$(date +%s.%N) - $start" | bc); \
	echo $dur >> jOut16_n1.t

done
